/**
 * Phase 1 model-agnostic harness — public surface.
 *
 * Built on @earendil-works/pi-ai per ADR-002. Everything here is either a
 * re-export of pi-ai's own ontology (1.2) or one of the four pieces the
 * harness genuinely owns: config routing (1.4), conversation state (1.5),
 * and tool dispatch (1.6).
 */

// 1.2 — schema/ontology
export type {
  AssistantMessage,
  Context,
  HarnessErrorKind,
  HarnessResult,
  Message,
  Tool,
  ToolCall,
  ToolResultMessage,
  Usage,
} from "./types.ts";
export { HarnessError } from "./types.ts";
export { errorMessage, errorResult } from "./harness-result.ts";
export { collectContextIssues, validateContext, type ContextIssue } from "./validate-context.ts";

// 1.4 — config + routing
export {
  DEFAULT_CONFIG_PATH,
  loadConfig,
  parseConfig,
  type ConfigEntry,
  type HarnessConfig,
} from "./config.ts";
export { callOptions, getModels, loadModel, type ResolvedModel } from "./load-model.ts";
export { complete, DEFAULT_RETRY_POLICY, type CompleteOptions } from "./complete.ts";
export {
  assistantMessageFingerprint,
  collectAssistantMessageIssues,
  inspectOllamaRuntime,
  type AssistantConformanceOptions,
  type OllamaRuntimeObservation,
} from "./conformance.ts";

// A0.1 — product-owned run/event protocol and audience projections.
export {
  assertRunEventSequence,
  collectRunEventIssues,
  collectRunEventSequenceIssues,
  isTerminalRunEvent,
  parseRunEvent,
  RUN_EVENT_SCHEMA_VERSION,
  RUN_EVENT_SENSITIVITY,
  RUN_EVENT_TYPES,
  RunEventValidationError,
  TERMINAL_RUN_EVENT_TYPES,
  type ApprovalRequestedPayload,
  type ApprovalResolvedPayload,
  type EventAudience,
  type EventSensitivity,
  type FullEventAudience,
  type JsonObject,
  type JsonPrimitive,
  type JsonValue,
  type CanonicalAudienceFor,
  type MessageCompletedPayload,
  type MessageDeltaPayload,
  type RunCancelledPayload,
  type RunBudgetUsage,
  type RunCompletedPayload,
  type RunEvent,
  type RunEventEnvelope,
  type RunEventOf,
  type RunEventPayloadMap,
  type RunEventSequenceOptions,
  type RunEventType,
  type RunFailedPayload,
  type RunStartedPayload,
  type RunUsage,
  type ToolCompletedPayload,
  type ToolDecisionPayload,
  type ToolRequestedPayload,
  type ToolStartedPayload,
  type TurnCompletedPayload,
  type TurnStartedPayload,
} from "./events.ts";
export {
  fingerprintContent,
  projectRunEvent,
  type AudienceRunEvent,
  type AudienceRunEventOf,
  type AuditMessageCompletedPayload,
  type AuditMessageDeltaPayload,
  type AuditRunEventPayloadMap,
  type AuditToolCompletedPayload,
  type AuditToolRequestedPayload,
  type ContentFingerprint,
  type OperationalMessageCompletedPayload,
  type OperationalMessageDeltaPayload,
  type OperationalApprovalRequestedPayload,
  type OperationalRunEventPayloadMap,
  type OperationalToolCompletedPayload,
  type OperationalToolRequestedPayload,
  type ProjectedRunCancelledPayload,
  type ProjectedEventType,
  type ProjectedRunEvent,
  type RunEventProjection,
  type ProjectedRunFailedPayload,
  type ProjectedToolDecisionPayload,
} from "./event-projections.ts";
export {
  checkpointForRunEvent,
  encodeRunEventSse,
  encodeSseFrame,
  eventsAfterCheckpoint,
  parseRunEventSseData,
  RunEventTransport,
  RunEventTransportError,
  runEventToSseFrame,
  type OptionalObserverFailure,
  type OptionalObserverFailureReason,
  type OptionalRunEventObserver,
  type RunEventCheckpoint,
  type RunEventSink,
  type RunEventTransportOptions,
  type ServerSentEventFrame,
} from "./event-transport.ts";
export {
  PRODUCT_MESSAGE_SCHEMA_VERSION,
  type ProductAssistantMetadata,
  type ProductAssistantPersistenceOutcome,
  type ProductAssistantStopReason,
  type ProductCostUsd,
  type ProductDiagnostic,
  type ProductDiagnosticError,
  type ProductImageBlock,
  type ProductMessageBlock,
  type ProductMessageEnvelope,
  type ProductMessageEnvelopeV1,
  type ProductMessageExtensions,
  type ProductMessageRole,
  type ProductMessageUsage,
  type ProductProviderExtensionBlock,
  type ProductProviderMetadata,
  type ProductRunCancelledMetadata,
  type ProductRunFailedMetadata,
  type ProductRunTermination,
  type ProductTextBlock,
  type ProductThinkingBlock,
  type ProductToolCallBlock,
  type ProductToolResultMetadata,
} from "./messages/envelope.ts";
export {
  collectProductMessageIssues,
  collectProductRunTerminationIssues,
  decodeProductMessageEnvelope,
  encodeProductMessageEnvelope,
  mapAssistantPersistenceOutcome,
  parseProductMessageEnvelope,
  parseProductRunTermination,
  ProductMessageMappingError,
  ProductMessageValidationError,
  ProductRunTerminationValidationError,
  productEnvelopeToRuntimeMessage,
  runtimeMessageToProductEnvelope,
  type RuntimeAssistantOutcomeOptions,
  type RuntimeMessageMappingOptions,
} from "./messages/codec.ts";
export {
  AttachmentRepository,
  ApprovalRepository,
  ConsumerCheckpointRepository,
  DurableJournalError,
  DurableJournalSink,
  DurableJournalUnavailableError,
  EncryptedEventSpool,
  ERASURE_STORES,
  AttachmentErasureStoreAdapter,
  ErasureCoordinator,
  ErasureError,
  ErasureRepository,
  ErasureVerificationError,
  EventJournalRepository,
  IdentityRepository,
  MessageRepository,
  OutboxRepository,
  PgSqlExecutor,
  RunRepository,
  RunHistoryProjector,
  JournalConsumer,
  SpoolCapacityError,
  SpoolCorruptionError,
  StorageDecodeError,
  SqlErasureStoreAdapter,
  ToolRepository,
  withPgTransaction,
  isDatabaseUnavailableError,
  type AppendMessageInput,
  type CheckpointStore,
  type ConsumerCheckpoint,
  type ErasureControlStore,
  type ErasureJob,
  type ErasureJobStatus,
  type ErasureRequestResult,
  type ErasureScope,
  type ErasureStore,
  type ErasureStoreAdapter,
  type ErasureSubjectType,
  type ErasureTarget,
  type ErasureTargetStatus,
  type DurableJournalSinkOptions,
  type EncryptedEventSpoolOptions,
  type EventSpoolEntry,
  type EventSpoolStats,
  type JournalAppendResult,
  type JournalConsumerOptions,
  type JournalDelivery,
  type JournalReader,
  type JournalWriter,
  type SqlExecutor,
  type SqlQueryResult,
  type PgQueryable,
  type StoredMessage,
  type StoredJournalEvent,
  type StoredRunStatus,
} from "./storage/index.ts";
export {
  AirGappedEgressGuard,
  collectResidencyInventoryIssues,
  EgressDeniedError,
  operationalLogLine,
  parseResidencyInventory,
  RESIDENCY_INVENTORY_SCHEMA_VERSION,
  RESIDENCY_STORE_IDS,
  ResidencyInventoryValidationError,
  type ResidencyContentMode,
  type ResidencyInventory,
  type ResidencyStore,
  type ResidencyStoreId,
  type ResidencyStoreState,
} from "./residency.ts";
export {
  ContextCompilationError,
  ContextCompiler,
  DEFAULT_RETRIEVED_CONTEXT_FRACTION,
  type CompiledProviderContext,
  type ContextBudgetSource,
  type ContextBudgetUsage,
  type ContextCompilationInput,
  type ContextCompilerOptions,
  type ContextHistoryTokenAnchor,
  type ContextProjectionSummary,
  type ContextTokenAllocation,
  type PromptFingerprint,
} from "./context/context-compiler.ts";
export {
  createPrefixPreservingCompactionStrategy,
  DEFAULT_PREFIX_COMPACTION_FRACTION,
  isPrefixCompactionMarker,
  PREFIX_COMPACTION_LAYOUT_VERSION,
  prefixPreservingCompactionStrategy,
  readPrefixCompactionManifest,
  type PrefixCompactionManifest,
  type PrefixPreservingCompactionOptions,
} from "./context/prefix-preserving-compaction.ts";
export {
  DEFAULT_SYSTEM_TEMPLATE_VERSION,
  delimitToolResult,
  delimitUntrustedToolResults,
  orderTools,
  PROMPT_LAYOUT_VERSION,
  renderSystemPrompt,
  retrievedContextMessage,
  UNTRUSTED_RETRIEVED_PREAMBLE,
  UNTRUSTED_TOOL_RESULT_PREAMBLE,
  type RetrievedContextItem,
  type VersionedSystemInstruction,
} from "./context/prompt-layout.ts";
export {
  buildStableCachePrompt,
  CACHE_CONFORMANCE_MINIMUM_PREFIX_TOKENS,
  CACHE_CONFORMANCE_SCHEMA_VERSION,
  CACHE_CONFORMANCE_WARM_REPEATS,
  cacheConformanceTools,
  mutateOneSystemPromptByte,
  planCacheConformanceProbes,
  runCacheConformanceTarget,
  type CacheCallObservation,
  type CacheConformanceTargetReport,
  type CacheProbeEvidence,
  type CacheProbeExecutor,
  type CacheProbeKind,
  type CacheProbeTiming,
  type RunCacheConformanceOptions,
} from "./cache-conformance.ts";
export {
  buildTruncationEvaluationHistory,
  planTruncationEvaluation,
  runTruncationEvaluationTarget,
  TRUNCATION_CONFORMANCE_SCHEMA_VERSION,
  TRUNCATION_EVALUATION_CONTEXT_WINDOW,
  TRUNCATION_EVALUATION_FACT_IDS,
  TRUNCATION_EVALUATION_OUTPUT_RESERVE,
  type EvaluatedTruncationStrategy,
  type RunTruncationEvaluationOptions,
  type TruncationCallObservation,
  type TruncationEvaluationTargetReport,
  type TruncationProbeEvidence,
  type TruncationProbeExecutor,
  type TruncationProbePhase,
  type TruncationProbeTiming,
  type TruncationStrategyEvidence,
} from "./truncation-conformance.ts";

// 1.7 — one transition of a conversation. Deliberately not a loop: the
// caller owns iteration, and this is the one place that turns a failure
// into a HarnessResult rather than a throw.
export {
  step,
  type StepDeps,
  type StepEventSink,
  type StepLifecycleEvent,
  type StepLifecycleSink,
  type StepResult,
} from "./step.ts";
export {
  run,
  type RunOptions,
  type RunReason,
  type RunResult,
} from "./run.ts";

// 1.5 — conversation state
export {
  capToolResult,
  ConversationManager,
  DEFAULT_MAX_TOOL_RESULT_CHARS,
  DEFAULT_RESERVE_TOKENS,
  type BudgetSource,
  type BudgetUsage,
  type ConversationManagerOptions,
  type LoadConversationOptions,
} from "./conversation-manager.ts";
export {
  dropOldestStrategy,
  estimateContextTokens,
  estimateOverheadTokens,
  estimateTokens,
  type TruncationStrategy,
} from "./truncation.ts";

// 1.6 — tool calling
export {
  dispatchToolCall,
  dispatchToolCalls,
  ToolRegistry,
  type ToolControlDeclaration,
  type ToolDispatchOptions,
  type ToolExecutionContext,
  type ToolHandler,
} from "./tool-registry.ts";
export {
  defaultToolExecutionController,
  fetchWithHttpPolicy,
  ToolExecutionController,
  validateShellExecution,
  WorkspaceConfinement,
  type HttpExecutionPolicy,
  type HttpPolicyDependencies,
  type ShellExecutionPolicy,
  type ShellExecutionRequest,
  type ToolConcurrencyLease,
  type ToolConcurrencyPolicy,
  type ValidatedShellExecution,
} from "./tool-execution.ts";
export {
  createDirectoryListTool,
  createFileReadTool,
  createFileWriteTool,
  createHttpFetchTool,
  createSearchTool,
  createShellTool,
  type FilesystemToolOptions,
  type FileWriteToolOptions,
  type HttpToolOptions,
  type SearchToolOptions,
  type ShellToolOptions,
} from "./tools/index.ts";
export {
  approvalArgumentsHash,
  APPROVAL_SCHEMA_VERSION,
  ApprovalResumeController,
  createApprovalRequest,
  parseApprovalRequest,
  type ApprovalAuthority,
  type ApprovalRequest,
  type ApprovalResolution,
  type ApprovalResumeOptions,
  type ApprovalResumeResult,
  type SubmittedApprovalDecision,
  type VerifiedApprovalDecision,
} from "./approval.ts";
export {
  mcpToolDiscoveryFingerprint,
  registerMcpServer,
  type McpCallToolResult,
  type McpClientPort,
  type McpDiscoveredTool,
  type McpListToolsPage,
  type McpRegistrationResult,
  type McpServerIdentity,
  type McpServerRegistrationConfig,
  type McpToolRegistration,
} from "./mcp/index.ts";
export {
  CapabilityPolicy,
  unconfiguredToolPolicyDecision,
  type CapabilityDecision,
  type CapabilityPolicyConfig,
  type CapabilityPolicyRule,
  type ToolPolicyContext,
  type ToolPolicyDecision,
  type ToolPolicyDecisionKind,
  type ToolPolicyInput,
  type ToolPolicySubject,
} from "./policy.ts";
export {
  AuthenticationError,
  bearerToken,
  bearerTokenSha256,
  FileSessionAuthenticator,
  hasPermission,
  parseSessionRegistry,
  readSessionRegistryFile,
  RegistrySessionAuthenticator,
  SESSION_REGISTRY_SCHEMA_VERSION,
  type ServerPermission,
  type ServerPrincipal,
  type ServerRole,
  type SessionAuthenticator,
  type SessionRegistry,
  type SessionRegistryEntry,
} from "./server/auth.ts";
export {
  PostgresIdentityStore,
  type DurableUserAccess,
  type IssuedSession,
} from "./server/identity-store.ts";
export {
  DurableApprovalGateway,
  PostgresApprovalStore,
  type ApprovalDecisionInput,
  type ApprovalGateway,
  type ApprovalResolutionResult,
  type PendingApprovalView,
} from "./server/approval-gateway.ts";
export {
  RunEventBroker,
  type LiveRunEventFailureHandler,
  type LiveRunEventListener,
} from "./server/event-broker.ts";
export {
  createSovereignHttpServer,
  DEFAULT_MAX_REQUEST_BYTES,
  DEFAULT_SSE_HEARTBEAT_MS,
  type AcceptedRunCommand,
  type RunCommandGateway,
  type RunCommandAcceptance,
  type RunEventReplayStore,
  type ServerAccessController,
  type ServerReadinessProbe,
  type SovereignHttpServerOptions,
} from "./server/http-server.ts";
export { PostgresServerAccessController } from "./server/storage.ts";
export {
  PostgresRunCommandStore,
  RunCommandConflictError,
  type AcceptRunCommandInput,
  type AcceptedRunOwnership,
} from "./server/command-store.ts";
export {
  parseServerDeploymentConfig,
  type ServerDeploymentConfig,
} from "./server/config.ts";
export {
  DeploymentOllamaRouteResolver,
  type DeploymentOllamaRouteOptions,
} from "./server/deployment-route.ts";
export {
  DurableRunCommandGateway,
  runCommandRequestHash,
  type DurableRunCommandGatewayOptions,
  type ResolvedRunRoute,
  type RunAdmissionLease,
  type RunProjectionDrain,
  type RunRouteResolver,
} from "./server/run-gateway.ts";
export {
  PostgresRunControlGateway,
  RunControlError,
  type AcquireRunControlInput,
  type RunControlGateway,
  type RunControlLease,
  type RunControlPolicy,
  type SettledRunUsage,
} from "./server/run-controls.ts";
export {
  PostgresProductReadStore,
  type ProductAttachmentRead,
  type ProductAuditRead,
  type ProductMessageRead,
  type ProductReadStore,
  type ProductRunRead,
} from "./server/product-reads.ts";

// 2.4 — memory sizing. Not part of the inference path; it is arithmetic
// over model metadata, used to decide what a given box can serve.
export {
  BITS_PER_WEIGHT,
  DEVICE_MEMORY_RESERVE_BYTES,
  estimateMemory,
  fitsIn,
  FIXED_OVERHEAD_BYTES,
  gb,
  kvBytesPerToken,
  maxContextFor,
  RUNTIME_BYTES_PER_TOKEN,
  type FitVerdict,
  type ModelGeometry,
  type SizingEstimate,
  type SizingInput,
} from "./sizing.ts";

// A0-M.1 — configured claims and live observations remain distinct. Future
// model selection must pass the freshness/health/requirement gate rather
// than treating deployment metadata as current evidence.
export {
  assessModelRoute,
  MODEL_CAPABILITY_SCHEMA_VERSION,
  ModelCapabilityRecordError,
  parseModelCapabilityRecord,
  type CapabilitySupport,
  type DeclaredCapabilityProvenance,
  type DeclaredModelCapabilities,
  type FeatureCapabilities,
  type ModelCapabilityRecord,
  type ModelCapabilityRecordV1,
  type ModelFeature,
  type ModelIdentity,
  type ModelRouteAssessment,
  type ModelRouteRequirements,
  type ObservedCapabilityProvenance,
  type ObservedModelCapabilities,
  type ReportingCapabilities,
  type ReportingCapability,
} from "./model-control/capabilities.ts";
export {
  LocalModelController,
  type AdmissionOutcome,
  type LocalAdmissionPolicy,
  type LocalAdmissionRequest,
  type LocalAdmissionResult,
  type LocalModelState,
  type LocalModelStatus,
  type LocalRuntimeAdapter,
  type LocalRuntimeSnapshot,
  type RunningLocalModel,
} from "./model-control/admission.ts";
export {
  OllamaRuntimeAdapter,
  parseOllamaProcessSnapshot,
  type OllamaAdapterOptions,
  type OllamaModelDescription,
} from "./model-control/ollama.ts";
export {
  distribution,
  percentile,
  PERFORMANCE_BASELINE_MINIMUM_SAMPLES,
  PERFORMANCE_BASELINE_SCHEMA_VERSION,
  summarizeDurationSamples,
  summarizePerformanceSamples,
  type DurationBaselineSummary,
  type DurationSample,
  type DistributionSummary,
  type PerformanceBaselineSummary,
  type PerformanceSample,
} from "./performance-baseline.ts";
